import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS course",
  description: "Generated by create next app",
  keywords: "next.js, react, javascript, js, jsx",
};

export default function Layout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header className='flex justify-center bg-gray-400'><h2>My Site Header</h2></header>
        {children}
        <footer className='flex justify-center bg-gray-400'><h2>My Site Footer</h2></footer>
      </body>
    </html>
  );
}
