import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS course",
  description: "Generated by create next app",
  keywords: "next.js, react, javascript, js, jsx",
};


export default function Layout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
